### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by m724tmy** [m724tmy/protospace-41327#1]
# URL
https://protospace-41327.onrender.com

**Comment by maru2628** [comment]
@m724tmy さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

**[修正依頼箇所]**

**ユーザー詳細機能**
- [ ] **ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移すること**
プロタイプ一覧のユーザー名をクリックしても、該当するユーザーの詳細ページに遷移できません。遷移できるようにしましょう。

https://github.com/user-attachments/assets/31cadbe4-b2c2-4c63-9324-f71a04df3acc

- [ ] **ログイン・ログアウトの状態に関わらず、ユーザーの詳細ページには、そのユーザーの詳細情報（名前・プロフィール・所属・役職）と、そのユーザーが投稿したプロトタイプが表示されていること**
「ユーザー名さんの情報」「ユーザー名さんのプロトタイプ」の「ユーザー名」となっているところは、該当するユーザーのユーザー名が入るようにしましょう。
該当するユーザー名が入るようにしましょう。

<img width="597" alt="スクリーンショット 2024-09-11 9 15 45" src="https://github.com/user-attachments/assets/2b35cdd2-c861-43a5-974d-19177df59a79">


修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下のProtoSpace完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by motomuun** [comment]
@m724tmy さん、再度ご提出頂きありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
